workflows:
  officelog_android:
    name: OfficeLog Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.matrimpathak.attendenceFlutter" # verify this
      groups:
        - keystore_credentials   # create in Codemagic UI
    scripts:
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get

      - name: Run tests (optional but recommended)
        script: |
          flutter test

      - name: Build APK
        script: |
          flutter build apk --release

      - name: Build App Bundle
        script: |
          flutter build appbundle --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab

    publishing:
      email:
        recipients:
          - your-email@example.com
  officelog_ios:
    name: OfficeLog iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.matrimpathak.attendenceFlutter" # verify this
      groups:
        - app_store_credentials   # create in Codemagic UI

    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: Run tests (optional)
        script: |
          flutter test

      - name: Build iOS IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - your-email@example.com
