import '../data/models/holiday.dart';

class IcsParser {
  /// Parses an ICS string and returns a list of Holiday objects.
  /// Note: The returned holidays will not have an ID or specific office locations
  /// assigned yet. Those should be handled when adding to Firestore.
  static List<Holiday> parseIcs(String icsString) {
    final List<Holiday> holidays = [];
    final lines = icsString.split('\n');

    bool inEvent = false;
    DateTime? dtStart;
    String? summary;

    for (var line in lines) {
      line = line.trim();
      if (line.isEmpty) continue;

      if (line == 'BEGIN:VEVENT') {
        inEvent = true;
        dtStart = null;
        summary = null;
      } else if (line == 'END:VEVENT') {
        if (inEvent && dtStart != null && summary != null) {
          holidays.add(
            Holiday(
              id: '', // Will be generated by Firestore
              date: dtStart,
              name: summary,
              officeLocations: [], // Default to empty, can be set later
              isRecurring: false, // Default to not recurring
            ),
          );
        }
        inEvent = false;
      } else if (inEvent) {
        if (line.startsWith('DTSTART;VALUE=DATE:')) {
          final dateStr = line.substring('DTSTART;VALUE=DATE:'.length).trim();
          if (dateStr.length >= 8) {
            try {
              final year = int.parse(dateStr.substring(0, 4));
              final month = int.parse(dateStr.substring(4, 6));
              final day = int.parse(dateStr.substring(6, 8));
              // Store as UTC to avoid local timezone shifts changing the day
              dtStart = DateTime.utc(year, month, day);
            } catch (e) {
              // Ignore invalid date formats
              print('Error parsing date: $dateStr - $e');
            }
          }
        } else if (line.startsWith('SUMMARY:')) {
          summary = line.substring('SUMMARY:'.length).trim();
          // Basic unescaping for common ICS characters
          summary = summary.replaceAll(r'\,', ',');
          summary = summary.replaceAll(r'\;', ';');
          summary = summary.replaceAll(r'\n', ' ');
          summary = summary.replaceAll(r'\N', ' ');
        }
      }
    }

    return holidays;
  }
}
